/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class MainPage extends javax.swing.JFrame {

    private CreateAccount currUser;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();

    }

    public MainPage(CreateAccount obj) {
        initComponents();
        setLocationRelativeTo(null);
        this.currUser = obj;
        System.out.printf("%s %s  %s %s %s %s\n", this.currUser.getFirstName(), this.currUser.getLastName(),
                this.currUser.getUsername(), this.currUser.getEmail(), this.currUser.getGender(), this.currUser.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addentry = new javax.swing.JButton();
        myEntries = new javax.swing.JButton();
        publicEntries = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MacBook_Air_-_9_50.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addentry.setBackground(new java.awt.Color(44, 182, 125));
        addentry.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addentry.setText("Add Entry");
        addentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addentryActionPerformed(evt);
            }
        });
        jPanel1.add(addentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 190, 40));

        myEntries.setBackground(new java.awt.Color(44, 182, 125));
        myEntries.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        myEntries.setText("View My Entries");
        myEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myEntriesActionPerformed(evt);
            }
        });
        jPanel1.add(myEntries, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 190, 40));

        publicEntries.setBackground(new java.awt.Color(44, 182, 125));
        publicEntries.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        publicEntries.setText("Public Entries");
        publicEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicEntriesActionPerformed(evt);
            }
        });
        jPanel1.add(publicEntries, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 190, 40));

        jButton4.setBackground(new java.awt.Color(44, 182, 125));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Log - Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 120, -1));

        exit.setBackground(new java.awt.Color(44, 182, 125));
        exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MacBook_Air_-_3_50.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.show(false);
        new SecondPage().show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addentryActionPerformed
        // TODO add your handling code here:
        this.show(false);
        try {
            new AddEntry(currUser).show();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addentryActionPerformed

    private void myEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myEntriesActionPerformed
        // TODO add your handling code here:
        this.show(false);
        try {
            new PrivateEntry(this.currUser).show();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_myEntriesActionPerformed

    private void publicEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicEntriesActionPerformed
        // TODO add your handling code here:
        this.show(false);
        try {
            new PublicEntry(this.currUser).show();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_publicEntriesActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addentry;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton myEntries;
    private javax.swing.JButton publicEntries;
    // End of variables declaration//GEN-END:variables
}
