/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author user
 */
public class PrivateEntry extends javax.swing.JFrame {

    private CreateAccount acc;
    private ArrayList<WriteEntry> write;

    java.sql.Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public PrivateEntry() {
        initComponents();

    }

    public PrivateEntry(CreateAccount obj) throws ClassNotFoundException, SQLException {
        initComponents();
        setLocationRelativeTo(null);
        this.acc = obj;
        write = new ArrayList();
        populateArrayList();
        printArrayList();
    }

    public void printArrayList() {
        for (int i = 0; i < write.size(); i++) {
            System.out.println("Title " + write.get(i).getEntryTitle() + " Text Body " + write.get(i).getEntryBody());
        }
    }

    // adding entries to arraylist from database
    public void populateArrayList() throws ClassNotFoundException, SQLException {
        Class.forName("oracle.jdbc.driver.OracleDriver");

        Connection con;
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##seproject", "123");

        try {
            PreparedStatement pst;
            String query = "SELECT ENTRY_TITLE, ENTRY_BODY FROM C##SEPROJECT.ENTRY where USERNAME = " + "'" + this.acc.getUsername() + "' and entry_type = 'private'";
            pst = con.prepareStatement(query);

            ResultSet rs;
            rs = pst.executeQuery(query);

            EntriesList.addItem("Entries");

            while (rs.next()) {
                String temp_eTitle = rs.getString("ENTRY_TITLE");
                String temp_eBody = rs.getString("ENTRY_BODY");

                EntriesList.addItem(temp_eTitle);
                write.add(new WriteEntry(temp_eTitle, temp_eBody));
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        EntriesList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Post = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(44, 182, 125));
        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, 30));

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 290, 240));

        EntriesList.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EntriesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntriesListActionPerformed(evt);
            }
        });
        getContentPane().add(EntriesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 290, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Entry");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, 30));

        Post.setBackground(new java.awt.Color(44, 182, 125));
        Post.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Post.setText("Post");
        Post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostActionPerformed(evt);
            }
        });
        getContentPane().add(Post, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MacBook_Air_-_9_50.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntriesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntriesListActionPerformed
        // TODO add your handling code here:
        int selectedIndex = EntriesList.getSelectedIndex();
        System.out.printf("Length: %d\n", write.size());
        if (selectedIndex > 0) {
            TextArea.setText("");
            TextArea.setText(write.get(selectedIndex - 1).getEntryBody());
        }

    }//GEN-LAST:event_EntriesListActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainPage(this.acc).show();
    }//GEN-LAST:event_backActionPerformed

    // returning the entry id of a particular user
    public int entry_id(String uname) throws ClassNotFoundException, SQLException {
        Class.forName("oracle.jdbc.driver.OracleDriver");

        Connection con;
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##seproject", "123");

        int abc = 0;

        try {
            PreparedStatement pst;
            String query = "select count(*) as \"EID\" from c##seproject.ENTRY where USERNAME = " + "'" + uname + "'";
            System.out.println(query);
            pst = con.prepareStatement(query);

            ResultSet rs;
            rs = pst.executeQuery(query);

            if (rs.next()) {
                abc = rs.getInt(1);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        return abc;
    }

    private void PostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostActionPerformed
        try {

            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##seproject", "123");

            System.out.println("entry id " + entry_id(this.acc.getUsername()));

            int entryId = entry_id(this.acc.getUsername());
            entryId++;
            String username = this.acc.getUsername();
            String entryTitle = EntriesList.getSelectedItem().toString();
            String entryType = "public";
            long millis = System.currentTimeMillis();
            java.sql.Date date = new java.sql.Date(millis);
            String entryBody = TextArea.getText();

            if (entryTitle.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Entry should have a tiltle");
                return;
            }

            if (entryBody.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please write something!");
                return;
            }

            // adding new entries to array list
            WriteEntry user = new WriteEntry(entryTitle, entryBody);
            write.add(user);

            String sql = "INSERT INTO ENTRY (ENTRY_ID, USERNAME, ENTRY_TITLE, ENTRY_TYPE, ENTRY_DATE, ENTRY_BODY) VALUES(?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(sql);

            pst.setInt(1, entryId);
            pst.setString(2, username);
            pst.setString(3, entryTitle);
            pst.setString(4, entryType);
            pst.setDate(5, date);
            pst.setString(6, entryBody);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Posted");

//            eTitle.setText("");
//            eBody.setText("");
            this.show(false);
            new MainPage(acc).show();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_PostActionPerformed

    
    // returning the entry id of a post for deleting a purpose
    public int del_entry_id(String uname) throws ClassNotFoundException, SQLException {
        Class.forName("oracle.jdbc.driver.OracleDriver");

        Connection con;
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "c##seproject", "123");

        int abc = 0;

        try {
            PreparedStatement pst;
            String query = "select count(*) as \"EID\" from c##seproject.ENTRY where USERNAME = " + "'" + uname + "'";
            System.out.println(query);
            pst = con.prepareStatement(query);

            ResultSet rs;
            rs = pst.executeQuery(query);

            if (rs.next()) {
                abc = rs.getInt(1);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        return abc;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrivateEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrivateEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrivateEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrivateEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrivateEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EntriesList;
    private javax.swing.JButton Post;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
